# Composite action for setup
name: 'Setup'
description: 'Setup Node and checkout code'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      shell: bash
