# Composite action for Allure report publishing
name: 'Allure Report Publishing'
description: 'Install Allure CLI and publish report'
runs:
  using: 'composite'
  steps:
    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev
      shell: bash
    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report
      shell: bash
    - name: Publish Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
        destination_dir: reports/${{ github.run_number }}
