# Composite action for Allure report publishing
name: 'Allure Report Publishing'
description: 'Install Allure CLI and publish report'
inputs:
  github_token:
    description: 'GitHub token for publishing to gh-pages'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev
      shell: bash

    - name: Generate Allure executor.json
      shell: bash
      run: |
        mkdir -p allure-results
        echo '{
          "name": "GitHub Actions",
          "type": "github",
          "reportUrl": "https://your-username.github.io/your-repo/reports/'${GITHUB_RUN_NUMBER}'/",
          "buildName": "'${GITHUB_RUN_NUMBER}'",
          "buildUrl": "https://github.com/'${GITHUB_REPOSITORY}'/actions/runs/'${GITHUB_RUN_ID}'"
        }' > allure-results/executor.json

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report
      shell: bash
    - name: Publish Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_branch: gh-pages
        publish_dir: allure-report
        destination_dir: reports/${{ github.run_number }}
